### PR TITLE
[USH-1631] Use only parameters for category in Mobile

### PR DESCRIPTION
**Pull request by Ifycode**
Fix:
Only parameters for categories in mobile

### CODE REVIEW

**Comment by Ifycode** [comment]
@Angamanga this needs the api helpers from the web client fix. 
Ready for review.

**Review by Angamanga — COMMENTED** [review]
Do we need mobile-development branch before merging this? I get an error when running it locally.

**Comment by Ifycode** [comment]
Yes @Angamanga 
See above comment: https://github.com/ushahidi/platform-client-mzima/pull/1498#issuecomment-2513495192

**Review by Angamanga — APPROVED** [review]
Works fine now 👍

**Pull request merged**
