### PR TITLE
Updates Language Input under post title.

### LINKED ISSUE #4731: update Language Input Under Post Title in Post Edit Modal In The Map View (Mobile Version)
Screenshot from 2023-08-31 11-36-28

---
Created automatically from USH-942 (https://linear.app/ushahidi/issue/USH-942/update-language-input-under-post-title-in-post-edit-modal-in-the-map)

### PR DESCRIPTION
**Pull request by nimishmedatwal**
This pull request aims at updating Language Input Under Post Title in Post Edit Modal and Add Post model In The Map View.
Fixes : [Issue#4731](https://github.com/ushahidi/platform/issues/4731)
Screenshots:
| Before | After |
| ------ | ----- |
| image | image |
| image | image |

### CODE REVIEW

**Comment by Angamanga** [comment]
Thank you for your PR @nimishmedatwal  🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

**Comment by Angamanga** [comment]
@ushahidlee Could you review please?

**Review by ushahidlee — APPROVED** [review]
Looks good

**Comment by Angamanga** [comment]
@Angamanga To consider for release

**Pull request merged**
