### PR TITLE
made successfull notification message clear

### PR DESCRIPTION
**Pull request by rajutkarsh07**
Resolving issue #838 

### Description
* Updated the popup message for successful import/upload of a survey from a CSV.
* Changed message from "JOB SUCCESS SUCCESS" to "JOB SUCCESS".

Frame 1 (2)

### CODE REVIEW

**Comment by Angamanga** [comment]
Thank you for your PR @rajutkarsh07  🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

**Comment by rajutkarsh07** [comment]
@Angamanga I have updated it

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution! 🙏

**Comment by Angamanga** [comment]
@Angamanga To consider for release

**Comment by Angamanga** [comment]
Closing since already fixed by another fix for another issue

**Pull request closed without merging**
