### PR TITLE
Select all survey button fix

### PR DESCRIPTION
**Pull request by kivenalaric**
So i realised there were 2 button clicks on the button, **(buttonClick)="toggleSidebarFilters('form')"** and **                (buttonClick)="clearFilter('form')"** where the **(buttonClick)="clearFilter('form')** was overriding the toggleSidebarFilters making it such that even when select all is clicked, it still tries to clear the list instead of toggling all checkboxes to be selected.

To See Solution.
=> Go to Data View,
=> Click on surveys,
=> Click on clear if any checkboxes are checked,
=> Click on select all,
=> It selects all checkbox survey categories.

Before, it didn't select all, it could clear all but not select all.

### CODE REVIEW

**Comment by kivenalaric** [comment]
@Angamanga please can you review my pr

**Comment by Angamanga** [comment]
Thank you for your PR @kivenalaric  🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

**Comment by kivenalaric** [comment]
> Thank you for your PR @kivenalaric 🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

Okay @Angamanga tho i dont know if i understand what you mean well because i wrote a small description of what i did when creating the pr. Or should i also add a video of how the checklist now works better?

**Comment by Angamanga** [comment]
@kivenalaric I meant something like this:
1. Go to data view
2. Click on...
So the reviewer can follow the steps and see the change

**Comment by kivenalaric** [comment]
> @kivenalaric I meant something like this:
> 
> 1. Go to data view
> 2. Click on...
>    So the reviewer can follow the steps and see the change

Okay @Angamanga  Just did in the pr description at the top.

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution @kivenalaric! Approved 👍

**Comment by Angamanga** [comment]
@Angamanga To consider for release

**Pull request closed without merging**
