### PR TITLE
fix - The On-boarding process has no multi-language support #4786

### PR DESCRIPTION
**Pull request by Felysilver**
---

## Issue adressed
https://github.com/ushahidi/platform/issues/4786

### What's new?

This pull request introduces a significant enhancement to our platform: **Multilingual Support for Guided Tours**. With this update, users around the globe can now enjoy guided tours in all languages supported by our platform, making our content more accessible and user-friendly for our diverse user base.

### Features

- **Comprehensive Language Coverage**: Access guided tours in every language supported by our platform.
- **Seamless Integration**: Smoothly integrated into the existing platform interface, ensuring a consistent user experience.

### Impact

- **Enhanced Accessibility**: This update opens up our platform to a wider audience, ensuring that more users can benefit from our guided tours in their native language.
- **Increased Engagement**: With tours available in multiple languages, we anticipate a boost in user engagement as content becomes more relatable and easier to understand.
- **Global Reach**: This feature is a step forward in our commitment to serving our global user base, breaking down language barriers to create a more inclusive digital environment.

### Screancasts

1. 
[china.webm](https://github.com/ushahidi/platform-client-mzima/assets/162261453/ce1bed17-de67-40ea-b276-52105eb49b7e)

2. 
[asia.webm](https://github.com/ushahidi/platform-client-mzima/assets/162261453/8d3edc32-a8bb-4ffe-a7d0-31a1163aa470)

4. 
[armenian.webm](https://github.com/ushahidi/platform-client-mzima/assets/162261453/d2218473-27b1-4e81-b89f-921cf0e583a4)

Fixed for all supported languages

Your feedback is invaluable. Please share your thoughts, suggestions, or any issues you encounter during testing. Let's make our platform truly global together!

---

### CODE REVIEW

**Comment by Felysilver** [comment]
Hi @Angamanga, could you please take a moment to review my PR regarding this issue? I’d greatly appreciate your insights. Thanks a lot!

**Comment by Angamanga** [comment]
@webong Could you please review this?

**Comment by Angamanga** [comment]
@webong Reminding you to review this PR 👍

**Review by webong — APPROVED** [review]
This is such a beautiful PR. Looks good to me.

**Pull request closed without merging**
