### PR TITLE
E2e tests for Survey Configuration - Hide author information

### PR DESCRIPTION
**Pull request by shakirandagire**
@AmTryingMyBest could you review this PR that handles [issues](https://github.com/ushahidi/platform-client-mzima/issues/722)

### CODE REVIEW

**Comment by theobadha** [comment]
We'll leave this in draft until data in the CI environment is updated.

**Comment by shakirandagire** [comment]
Noted thanks for the heads up

**Comment by theobadha** [comment]
@shakirandagire I'll hand this back to you, it should be good to review and merge. I was incorrectly expecting to see author name while the user privilege in use didn't allow for it ( explaining the many commits) 
The one thing to note in this PR is that I moved the login tests into one login file but each function under it's own, well, function.

**Review by theobadha — COMMENTED** [review]
Changes implemented in conversation.

**Comment by shakirandagire** [comment]
@AmTryingMyBest Thanks for the update on the PR. Let me look through it.

**Review by shakirandagire — COMMENTED** [review]
Changes look good to me as the tests pass as expected.
We could just do a bit of cleaning up of the file to remove commented out code but it is not a blocker for merge

**Pull request merged**
