### PR TITLE
[USH-918] Rename menu-list-non-links Angular component name to better reflect its purpose 

### PR DESCRIPTION
**Pull request by MugoBrian**
This fix is to improve the solution for this issue #624 
Fix:
Edited the component names in the menu-modal-popups.component.spec.ts to match the updated names.

### CODE REVIEW

**Comment by Ifycode** [comment]
is this ready for review? @MugoBrian

**Comment by Ifycode** [comment]
- Use/copy and paste the issue title as the title for your PR
- Link the issue too
@MugoBrian

**Comment by MugoBrian** [comment]
> * Use/copy and paste the issue title as the title for your PR
> * Link the issue too
>   @MugoBrian

@Ifycode , yes the PR is ready for review. I have made the necessary changes as per your request.

**Review by Ifycode — APPROVED** [review]
Approved. Thank you @MugoBrian

**Pull request merged**
