### PR TITLE
[Outreachy Task Submission] fix "change_laguage" to "change_language"

### PR DESCRIPTION
**Pull request by Chiemezuo**
# Introduction
Just a simple typo fix.

### CODE REVIEW

**Comment by Chiemezuo** [comment]
@tuxpiper could you have a look at this?

**Comment by tuxpiper** [comment]
Thank you @Chiemezuo for keeping an eye on our English writing standards :) . Approved :+1:

**Comment by tuxpiper** [comment]
@Angamanga  , post-approval ping for Outreachy

**Comment by Chiemezuo** [comment]
@tuxpiper The pleasure is all mine. Thank you!! 🥳

**Pull request merged**
