### PR TITLE
Improved The Webpage Print Layout

### PR DESCRIPTION
**Pull request by MugoBrian**
This fix is for this [issue](
https://github.com/ushahidi/platform/issues/4141)

Fixes:

1. **Streamlined layout:** The sidebar and toolbar have been removed to avoid unnecessary elements on printed pages.
2. **Enhanced readability:** Post cards have been adjusted to a more suitable width for printed content.
3. **Visual improvement:** A border has been added to posts for a cleaner and more visually appealing presentation on printed pages.

See screenshot below.
Screenshot from 2024-03-09 15-39-07

### CODE REVIEW

**Comment by MugoBrian** [comment]
Progress Update:
Hello @Angamanga and @Ifycode , I have made some progress but has some challenges:

1. Spacing between the posts  (I have tried using Flexbox and Grid, but nothing worked)
2. The content to fill the whole page /width of the printing page. (I have tried width:100% for the main,content-wrapper, and the feed posts, but none worked).

**Comment by Aquilaafuadajo** [comment]
Hi @MugoBrian following up with our conversations on discord, here is my suggestion: 

An easy way out of this is to use the dev tools to inspect the element. Tweak the styles in the dev tools till you get your desired outcome, then start to add this modifications to your print block.
width: 100% isn't working because the element is being blocked by margins
After playing around with this in my dev tools, I came up with this to fix the issue you're having 👇 

```
@media print {
  .sidebar,
  .mobile-page-nav,
  app-toolbar {
    display: none;
  }
  .main {
    height: unset;
    overflow: scroll;
  }

  .content-wrapper {
    width: 100%;
    border: 1px solid black;
  }

  .feed-page {
    margin: 0px !important;
  }

  .mat-drawer-container {
    .mat-drawer-content {
      margin: 0px !important;
    }
  }
}

```
more work can still be done to improve the print outcome but I think if you try to use the approach I just told you, you should get it right

**Comment by MugoBrian** [comment]
Hello @Angamanga. This PR is ready for review, took a bit longer than I expected. Finally, I have managed to make some tweaks to the print page layout (see screenshot below).

Screenshot from 2024-03-15 08-25-08

Steps To Reproduce The Fix:

1. Go to data view
2.  Click on fn+command+p  (For Mac) or Ctrl + P (Windows & Linux) for shortcut or file then print

**Review by Angamanga — CHANGES_REQUESTED** [review]
Thank you @MugoBrian, this is sooo much better than previously! I noticed one thing, this change affects the map-view, it just returns a blank page, and I think its something to do with this change, because I see the map in other branches. Is there any way you could make the change more specific to only affect the data-view?

**Comment by MugoBrian** [comment]
Hello @Angamanga . I will check it out.

**Comment by MugoBrian** [comment]
I have submitted a fix, could kindly review it @Angamanga

**Review by Angamanga — APPROVED** [review]
Excellent! Thank you @MugoBrian

**Comment by Angamanga** [comment]
@Angamanga To consider for next release

**Pull request closed without merging**
