### PR TITLE
[#4734] Change Confirmation message text

### PR DESCRIPTION
**Pull request by goodylove**
### Description
This pull request addresses the issue of unclear confirmation message text by updating it to provide users with more informative feedback.

### Changes Made
- Updated confirmation message text from "Post Status have been changed" to "Post Status Changed"
  - Old Text: "Post Status have been changed"
  - New Text: "Post Status Changed"

### Testing
I have tested the updated confirmation message text by:
- Verifying its display in various scenarios.
- Ensuring it aligns with the expected message text.

### CODE REVIEW

**Comment by Angamanga** [comment]
Thank you for your PR @goodylove  🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

**Comment by goodylove** [comment]
> Thank you for your PR @goodylove 🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

ok i will do that now

**Comment by goodylove** [comment]
@Angamanga i have updated my PR

**Comment by Angamanga** [comment]
@webong Could you please review?

**Comment by Angamanga** [comment]
@webong Reminding you to review this PR 👍

**Review by webong — APPROVED** [review]
This passes code review check ... only thing is I don't see how the old notification message is quite unclear compared to the new one.

Feels the same to me, in my opinion.

**Pull request closed without merging**
