### PR TITLE
[Fix] User Name and email not available past a certain zoom level or page size

### PR DESCRIPTION
**Pull request by Aquilaafuadajo**
Hello @Angamanga, I made an attempt on this [#4728 ](https://github.com/ushahidi/platform/issues/4728), please help review 🙏🏽 
here's a video of what it looks like now 👇🏽 

https://github.com/ushahidi/platform-client-mzima/assets/46582086/22e7e6e7-7f36-49c3-a1de-2a8c53ffa1c5

### CODE REVIEW

**Comment by Angamanga** [comment]
@Aquilaafuadajo Thank you! I will review shortly!

**Comment by Aquilaafuadajo** [comment]
Thank you @Angamanga I'll appreciate every feedback 🙏

**Comment by Angamanga** [comment]
Hi @Aquilaafuadajo! Thank you for this! I think a good solution would be to move the name and the email to the little dropdown that appears when clicking on the user-avatar instead. It moves the information from the main-screen to save space and avoid cluttering the header, but the information would still be visible when clicking on the dropdown-arrow. Would you mind doing an attempt solving that?

**Comment by Aquilaafuadajo** [comment]
That makes more sense. Thank you @Angamanga, I'll make this change

**Comment by Aquilaafuadajo** [comment]
@Angamanga I have made the requested fixes. I also noticed the username and email doesn't appear anywhere on mobile too so I added the dropdown to mobile too. I could also add it to the side menu below the deployment name, but I don't want to mix the information together. Please let me know what you think about this.

Below is a video of the new changes 👇🏽 

https://github.com/ushahidi/platform-client-mzima/assets/46582086/f2c452dc-6bc4-4883-aed2-532671398e00

**Review by Angamanga — APPROVED** [review]
Very nice! Thank you @Aquilaafuadajo!

**Comment by Angamanga** [comment]
@Mh-Asmi To consider for next release 👍

**Comment by Angamanga** [comment]
@Angamanga

**Pull request merged**
