### PR TITLE
[Outreachy Task Submission] Fixing NODE_ENV script issues for Windows

### LINKED ISSUE #789: 'NODE_ENV' is not recognized as an internal or external command
### Subject:
Issue with setting up Platform-client-mzima mobile app on Android Studio

Hello @tuxpiper, @AmTryingMyBest,  @Ifycode 

I hope you're doing well. I'm currently working on setting up the Platform-client-mzima project and have encountered an error while trying to run the mobile app on a simulator in Android Studio. I would appreciate your assistance in resolving this issue.
Here are the details:

### Steps taken:

- [x] Successfully set up the Platform-client-mzima project for the web.
- [x] Set up the mobile application on the web, following the provided setup guide.
- [x] Attempted to run the mobile app on a simulator in Android Studio.
### Error encountered:
I received the following error message:

failed

 ### Expected behavior: 
 I expected the mobile app to run on the simulator without any errors, similar to the successful setup of the web version.I have already followed the setup guide and reviewed some of the mobile scripts, which appear to be working perfectly. However, I'm unsure about the cause of this specific error.Could you please review my steps and let me know if there's anything I might have missed or any additional configurations required to resolve this issue? Your guidance and assistance would be greatly appreciated

### PR DESCRIPTION
**Pull request by Chiemezuo**
# Introduction
This fixes #789 
Windows isn't very compliant with the UNIX way of setting environment variables, and thus certain scripts that require setting environment variables will fail.

## How to test this PR
**Note**: You will need a Windows computer.
1. Navigate to your project root (`[your-directory]/platform-client-mzima/`) in your command line on a Windows PC.
2. Run `npm run mobile:android`.
3. Notice that you will see a `'NODE_ENV' is not recognized as an internal or external command...` error.
4. Checkout to this PR.
5. Repeat step 2.
6. This time around, it works.

## Extra comments:
I used the `cross-env` library, and updated the scripts in the `project.json` file that set the `NODE_ENV` in the `mobile-mzima-client` directory.

### CODE REVIEW

**Review by tuxpiper — APPROVED** [review]
Nice work @Chiemezuo 👍

**Comment by Chiemezuo** [comment]
Thank you @tuxpiper 🥳

**Comment by tuxpiper** [comment]
@Chiemezuo I'm curious, any reason other commands like "build" were not covered?

**Comment by Chiemezuo** [comment]
@tuxpiper my apologies. I think I may have missed them. 😅
I was trying to limit the PR to the scope of the issue itself that was raised.

**Comment by Chiemezuo** [comment]
But I could raise another PR for those. @tuxpiper

**Comment by tuxpiper** [comment]
> I was trying to limit the PR to the scope of the issue itself that was raised.

Makes sense :) Not a bad choice.

> But I could raise another PR for those. @tuxpiper

Thank you 🙏  No need for another PR. Maybe you could add another commit on your fork branch so that it ends up in this same PR?

**Comment by Chiemezuo** [comment]
Yes, yes, that works @tuxpiper 
So, that's adding the `cross-env` to `build` commands?
I want to be sure I got you right.

**Comment by tuxpiper** [comment]
> @Chiemezuo I'm curious, any reason other commands like "build" were not covered?

Oh my bad, actually I'm going to answer my own question here. There are no environment variables set for those commands.

So, no changes needed.

**Comment by Chiemezuo** [comment]
Ah, lovely!
I was reading and replying your messages via GitHub mobile, so I couldn't see the full code.
Regardless, cheers!! 🥳

**Comment by tuxpiper** [comment]
@Angamanga post-approval ping

**Pull request merged**
