### PR TITLE
[Outreachy Task Submission]  Fixed User is not notified when a post is added to a collection(s) successfully.

### PR DESCRIPTION
**Pull request by claire256**
**PR DESCRIPTION**
This PR addresses the issue of, when a user adds a post to a "collection or collections", the user is not notified and the modal does not close. To improve user experience, a user should get a notification that the collection has been added successfully.

**How to Test**

1. Login
2. Click "Data View"
3. Select a "Post"
4. Click the "ellipsis" and select "Add to Collection"
5. Select a collection(s).

**Link to the issue**
https://github.com/ushahidi/platform/issues/4861

**Screenshot**
Add post to collection

### CODE REVIEW

**Comment by claire256** [comment]
@Angamanga could you kindly look at this.

**Review by tuxpiper — APPROVED** [review]
Thank you for raising the issue and making this contribution. Nice one 👍

**Comment by tuxpiper** [comment]
@Angamanga post-approval ping

**Comment by claire256** [comment]
Thank you @tuxpiper

**Pull request closed without merging**
