### PR TITLE
 [Outreachy Task Submission] Fix Dropdown Icon Behavior in Account Settings and Logout Dropdown Menu (#4782)

### PR DESCRIPTION
**Pull request by mhdamaan79**
This PR resolves an issue [(ushahidi/platform#4782)](https://github.com/ushahidi/platform/issues/4782) where the dropdown icon in the "account settings and logout menu" fails to respond to user interaction. Previously, when users attempted to access the "account settings and logout menu" dropdown menu by clicking on the dropdown icon next to their name and email, the icon remained stuck in the downward arrow position, failing to toggle between the upward and downward arrow positions to indicate the opening and closing of the dropdown menu.

**Changes Made:**

- Fixed the dropdown arrow icon to rotate when the "account settings and logout" menu is opened.
- Ensured the arrow icon returns to its default position when the menu is closed.

### Before:
**Video**
https://github.com/ushahidi/platform/assets/118375524/cad1d503-9d52-4ee0-bc5a-5c2ec7fdee2a

**Screenshot**
Screenshot 2024-03-09 132051

### After:
**Video**
https://github.com/ushahidi/platform-client-mzima/assets/118375524/f610599b-89ec-4589-84ce-7560e1e1d152

**Screenshot**
Screenshot 2024-03-09 194027

### CODE REVIEW

**Review by Angamanga — CHANGES_REQUESTED** [review]
Thank you for this finding 🙏 It works fine! However, there has been changes in this specific code in the development-branch since you added this change so there is a conflict in the code. Could you merge development to your branch and resolve the conflicts? Thanks :)

**Comment by mhdamaan79** [comment]
> Thank you for this finding 🙏 It works fine! However, there has been changes in this specific code in the development-branch since you added this change so there is a conflict in the code. Could you merge development to your branch and resolve the conflicts? Thanks :)

Hey @Angamanga could you please review my latest changes and let me know if any further adjustments are needed? Thank you!

**Review by Angamanga — APPROVED** [review]
Thank you! Works fine now!

**Comment by Angamanga** [comment]
@Angamanga To consider for release

**Pull request closed without merging**
