### PR TITLE
[Outreachy Task Submission] Improve text description for number of posts in collection

### PR DESCRIPTION
**Pull request by RWUBAKWANAYO**
### Description
This pull request addresses issue ushahidi/platform#4727 for improving the text description for the number of posts displayed in each collection. Previously, only the number of posts was shown, which could be unclear to users.

### Changes Made:
- Added descriptive text to indicate the number of posts available in each collection.
- Modified styles to ensure proper alignment and visual presentation of the text description.

### Testing Checklist:
1. Start the mobile app with `npm run mobile:serve`.
2. Select the deployment (e.g., accessibility_ushahidi).
3. Click on the profile icon and either log in or sign up.
4. Click on the profile icon again and select "Collection".
5. Verify that you see a list of collections with the associated number of posts in each collection.
6. Confirm that the added descriptive text for the number of posts is displayed correctly.
7. Ensure proper alignment and visual presentation of the text description.

https://github.com/ushahidi/platform-client-mzima/assets/68381641/20856167-59b5-420b-8568-2c8290fba345

### CODE REVIEW

**Comment by Angamanga** [comment]
Thank you for your PR @RWUBAKWANAYO  🙏. Could you please add a checklist for testing the fix as well and then we'll review it 👍

**Comment by RWUBAKWANAYO** [comment]
@Angamanga, I'm unsure about what else to include in this PR. Should I be adding tests for the changes I made? Can you please give me more details? Thanks.

**Comment by Angamanga** [comment]
@RWUBAKWANAYO Just a checklist in text above in the PR-description with steps on how to get to the affected screen and see the changes you have made 👍

**Comment by RWUBAKWANAYO** [comment]
@Angamanga, I've added the testing checklist as requested. Could you give it a look when you get a chance? Thanks!

**Review by Angamanga — APPROVED** [review]
Thank you for your submission! This works fine 🙏

**Comment by Angamanga** [comment]
@Angamanga To consider for release

**Pull request closed without merging**
