### PR TITLE
fix notification when a survey is deleted, all collected data from the Survey is lost #4740

### PR DESCRIPTION
**Pull request by Felysilver**
A confirmation modal comes up when deleting a Survey. And it has been displaying this to the UI "Deleting this survey will remove it from database. This action cannot be undone."

The requirement of this https://github.com/ushahidi/platform/issues/4740 issue reported by @tuxpiper 
was to change change this message to "Deleting this survey will remove it and all collected data from the database. This action cannot be undone." As I have implement. So with this everything must be fixed about this issue.

### CODE REVIEW

**Comment by Felysilver** [comment]
@tuxpiper, @Angamanga, may you please look at my PR

**Comment by MugoBrian** [comment]
Hello @Felysilver. The link redirects to this link https://github.com/ushahidi/platform-client-mzima/pull/url which results to  " 404 page not found". 

Could you confirm this?

**Comment by Angamanga** [comment]
@Felysilver Thank you! I will review shortly!

**Comment by Felysilver** [comment]
Thanks @MugoBrian I think the problem was the implementation of markdown and I decided to directly paste in the link. Now it is working.

**Comment by Angamanga** [comment]
Thank you for the PR @Felysilver! Please add a short step by step checklist on how to test your changes when reviewing the PR 👍

**Comment by Angamanga** [comment]
@ushahidlee Could you review this one please?

**Review by ushahidlee — CHANGES_REQUESTED** [review]
Hi @Felysilver, 

This change is great but you have modified the Arabic i18n json. Could you please make this change on en.json instead?

**Comment by Felysilver** [comment]
> Hi @Felysilver,
> 
> This change is great but you have modified the Arabic i18n json. Could you please make this change on en.json instead?
@ushahidlee, thanks for the review, I have update the pr to reflect the changes you asked for.

**Pull request closed without merging**
