### PR TITLE
Rename the menu-list-links to menu-nav-views

### PR DESCRIPTION
**Pull request by MugoBrian**
This is a fix for the issue #623. @Ifycode, could you kindly review it?

### CODE REVIEW

**Comment by Ifycode** [comment]
Interesting that you have conflict @MugoBrian 
For this particular task I don't think you should not be having conflicts, because you are only updating what was there and that nobody else has touched recently.

**Comment by Ifycode** [comment]
Ah, I probably see why. You are dealing with and sending PR into the Hacktoberfest-2023 branch. That branch is complicated due to rebasing which has altered the git commit history. I only use it for the merge purpose to achieve a clean merge without having to have an extra merge commit too.

**What to do:** Close this PR and use the development branch as stated here, and you should be fine https://github.com/ushahidi/platform-client-mzima#how-to-make-and-submit-changes-to-this-repository

@MugoBrian

**Comment by MugoBrian** [comment]
> Ah, I probably see why. You are dealing with and sending PR into the Hacktoberfest-2023 branch. That branch is complicated due to rebasing which has altered the git commit history. I only use it for the merge purpose to achieve a clean merge without having to have an extra merge commit too.
> 
> **What to do:** Close this PR and use the development branch as stated here, and you should be fine https://github.com/ushahidi/platform-client-mzima#how-to-make-and-submit-changes-to-this-repository
> 
> @MugoBrian

Hello @Ifycode. I got confused when I saw the previously closed PRs, that hacktoberfest-2023 was the base branch and you were merging the commits into that branch.

Thank you for the heads up, the link you provided doesn't explicitly state the base branch for the PR is development or did I miss that somewhere in between?

Let me do as per your instructions. Thank you once again 💪🏾

**Comment by Ifycode** [comment]
Although, this has been answered in "closed doors", I'll give the answer openly since I find it's been asked here too @MugoBrian 

To your question, the section started with "Except you are requested to create your branch from another branch... ". 
And then the end says: "Then send a pull request for your changes to be reviewed".

The default base branch of the repo has already been set to the branch that contributions/PRs should be submitted to. To avoid sending the PR to the wrong place/branch. You will find this approach is being used in many contribution settings. 

There is no expectation that you should change the base branch, except otherwise informed to do so. And there is no where in the hacktoberfest discussion/docs that indicates changing of the branch.

It's great that you are able to notice this, but then incase of next time, try not to overthink it. I say this because you seem to be observant. So I will help you by sharing the PR for which the hacktoberfest-2023 branch is connected to (maybe reading the comment on that PR might help understand it better): 
- https://github.com/ushahidi/platform-client-mzima/pull/631

That said, you can always ask questions for anything that confuses you, and we will gladly help you to understand.

#

The idea is to keep the doc simple and easy to understand based on the things we have put in place. If you feel that that part needs to be corrected you can raise an issue for it, so that you or others can attempt fixing it.

**Comment by MugoBrian** [comment]
> Although, this has been answered in "closed doors", I'll give the answer openly since I find it's been asked here too @MugoBrian
> 
> To your question, the section started with "Except you are requested to create your branch from another branch... ". And then the end says: "Then send a pull request for your changes to be reviewed".
> 
> The default base branch of the repo has already been set to the branch that contributions/PRs should be submitted to. To avoid sending the PR to the wrong place/branch. You will find this approach is being used in many contribution settings.
> 
> There is no expectation that you should change the base branch, except otherwise informed to do so. And there is no where in the hacktoberfest discussion/docs that indicates changing of the branch.
> 
> It's great that you are able to notice this, but then incase of next time, try not to overthink it. I say this because you seem to be observant. So I will help you by sharing the PR for which the hacktoberfest-2023 branch is connected to (maybe reading the comment on that PR might help understand it better):
> 
> * [Combined fixes: Hacktoberfest 2023 #631](https://github.com/ushahidi/platform-client-mzima/pull/631)
> 
> That said, you can always ask questions for anything that confuses you, and we will gladly help you to understand.
> 
> The idea is to keep the doc simple and easy to understand based on the things we have put in place. If you feel that that part needs to be corrected you can raise an issue for it, so that you or others can attempt fixing it.

Thank you for this. I will try not to overthink.So should I still create the issue still as discussed previously?

**Pull request closed without merging**
