### PR TITLE
E2e disable user signup

### LINKED ISSUE #667: e2e-disable user sign up
Sign ups can be disabled for deployments. As a result, the Sign Up link is not available

- [ ] Log in as admin
- [ ] Navigate to settings
- [ ] Click on Disable User sign up
- [ ] Save changes
- [ ] Verify the Disable user sign up checkbox stays checked
- [ ] Log out
- [ ] Verify the Sign Up link is unavailable. Log in button should have only Log In fields and no Sign up links

### PR DESCRIPTION
**Pull request by oyenuga17**
Resolves #667 

@AmTryingMyBest please help review 😊 🙏

### CODE REVIEW

**Comment by theobadha** [comment]
@oyenuga17 please quick change, move the settings.cy file into the Settings folder right next to general.cy file and not inside its own folder called settings. Rename it to something like sign-up or something.

**Comment by oyenuga17** [comment]
> @oyenuga17 please quick change, move the settings.cy file into the Settings folder right next to general.cy file and not inside its own folder called settings. Rename it to something like sign-up or something.

Okay. On it

**Comment by oyenuga17** [comment]
@AmTryingMyBest please hold on a bit this. I'm trying to group the functions and locators in to one file too

**Comment by oyenuga17** [comment]
@AmTryingMyBest This is good to go now

**Comment by theobadha** [comment]
Good. Thank you!

**Pull request merged**
