### PR TITLE
[Outreachy Task Submission] Fix Accessibility Tree Order

### LINKED ISSUE #4850: [Outreachy Task Submission] Fix Accessibility Tree Order
The accessibility tree on the data view page is not in order

### PR DESCRIPTION
**Pull request by Aquilaafuadajo**
Should resolve [#4850](https://github.com/ushahidi/platform/issues/4850)

**Description**

Currently the Accessibility Tree on the data view page is not in order. In the video below 👇🏽 when navigating using tab, when the focus gets to the filter button, instead of proceeding to the share button as the next item in the accessibility tree it skips it and jumps directly to the survey filters and after that it focuses on filter components that are not visible. 

https://github.com/ushahidi/platform-client-mzima/assets/46582086/ad127e37-1cba-4aaa-b0f1-37a6469dff8a

**Why does this happen?**
This happens because the survey filters and main filters are embeded inside the search-form component, so technically the filter components come before the share button in the accessibility tree. 👇🏽 
Screenshot 2024-03-23 at 22 44 11

**Proposed Fix**

In this pr I have refactored the search-form component and move the filters outside of the search component. I plan to move the search and filter functionality to the toolbar component and pass the necessary functions down as props.

**Progress Made**

I have successfully separated the search-form component from the filter components and here's the result 👇🏽 

https://github.com/ushahidi/platform-client-mzima/assets/46582086/0a066fba-d13e-4117-a83c-70d2945e3104

**What's Left?**

- Move search and filter functionalities up to toolbar component
- Remove duplicate functions/methods from child components (survey-filters, search-form, main-filters)
- Remove duplicate css from child components (survey-filters, search-form, main-filters)

@Angamanga This is huge refactor in the code and I'll need your feedback/approval to continue with this. 🙏🏽

### CODE REVIEW

**Comment by Angamanga** [comment]
@Aquilaafuadajo Yes, this is a huge refactor :D It looks promising and I suggest you continue, if nothing else as for the learning-experience. There are ongoing work on the filters right now so I cannot guarantee it will be merged. I also know for a fact that anytime someone touches the filters a huge number of new issues arise 🙈 . So try testing your work extremely well (manual testing) and also look at places where you would not expect to see issues, they are so tangled up with everything unfortunately.

**Comment by Aquilaafuadajo** [comment]
Okay @Angamanga, I'll continue. Thanks for the heads up 😅 I'll ensure I test and test until this is done 💪🏽

**Comment by Aquilaafuadajo** [comment]
@Angamanga This was a tough one but I managed to crack it😅. I've finally been able to extract each components and moved the data and methods to the toolbar component. Right now everything works as expected but I'm still conducting series of manual testing and comparing with staging to be sure I don't miss anything. 

I'm learning a lot about angular from this task so I'll keep researching for new ideas to make this better and keep improving it. 💪🏽

**Comment by MugoBrian** [comment]
Hello @Aquilaafuadajo. Firstly, great work! Secondly, I'm curious about the focus indicator's behavior when the user navigates to the account drop-down menu. After the user tabs again, where should the focus indicator move to next? Since I pulled your changes, I noticed that the focus has disappeared, and I'm uncertain which part of the platform it moves to.

**Comment by Aquilaafuadajo** [comment]
Hey @MugoBrian thanks for testing this out. I saw this problem yesterday and fixed it, I just realized I didn't push. Will push now 👍🏽

**Comment by MugoBrian** [comment]
Hello @Aquilaafuadajo. I will check it out. It also seems this branch has conflicts. Is that correct on your end?

**Pull request closed without merging**
