### PR TITLE
[USH-931] Mobile client: UI drafting error

### PR DESCRIPTION
**Pull request by MMwandigha**
- FIxed .foundedDeploymentList variable to .foundDeploymentList
- Fixed typo that showed 'founded' to 'found' when searching for deployments

### CODE REVIEW

**Comment by Ifycode** [comment]
@MMwandigha is this PR ready for review?

#

PS: You can always let reviewers know if your pull request is ready for review by indicating as a comment of your PR. Or use the reviewers select dropdown on the PR to alert reviewers to help you take a look at your PR.

**Comment by MMwandigha** [comment]
@Ifycode Yes, it is ready for review

**Comment by MMwandigha** [comment]
> @MMwandigha is this PR ready for review?
> 
> PS: You can always let reviewers know if your pull request is ready for review by indicating as a comment of your PR. Or use the reviewers select dropdown on the PR to alert reviewers to help you take a look at your PR.

Noted. Thanks

**Comment by Ifycode** [comment]
Just copy the issue title and paste it as the pull request title, so that it is easy to track for me (and other reviewers generally) @MMwandigha

**Comment by MMwandigha** [comment]
Noted. I have changed it to the Issue title

**Comment by Ifycode** [comment]
Please see example PR @MMwandigha 
- https://github.com/ushahidi/platform-client-mzima/pull/657

**Comment by MMwandigha** [comment]
> Please see example PR @MMwandigha
> 
> * [[USH-919] Add pull request template for platform client (mzima) #657](https://github.com/ushahidi/platform-client-mzima/pull/657)

Can you confirm if this is okay?

**Comment by Ifycode** [comment]
Review in progress @MMwandigha 
I will definitely update you 👍🏼

**Review by Ifycode — CHANGES_REQUESTED** [review]
Nice work @MMwandigha 
Your package-lock file also changed content here. Please revert package-lock to it's original state so that it doesn't show up as one of the files changed.

**Comment by MMwandigha** [comment]
@Ifycode Please review the changes I have just made

**Review by Ifycode — APPROVED** [review]
Nicely done @MMwandigha 
Approved!

**Pull request merged**
