### PR TITLE
[USH-1248] Improving the search for existing Collections

### PR DESCRIPTION
**Pull request by MMwandigha**
Functionality that allows collections to load before pressing the return key

### CODE REVIEW

**Comment by MugoBrian** [comment]
Hello @MMwandigha. You didn't have to push the env.json changes, since the default backend_url is localhost:8080.

**Comment by MMwandigha** [comment]
Noted @MugoBrian I've tried reverting the changes of this file

**Comment by MugoBrian** [comment]
> Noted @MugoBrian I've tried reverting the changes of this file

Has reverting helped?

**Comment by MMwandigha** [comment]
> > Noted @MugoBrian I've tried reverting the changes of this file
> 
> Has reverting helped?

Actually, it didn't work as I had expected, it turns out that I couldn't reset the commit and push it again, so I modified the .json file back to its original format.

**Comment by MugoBrian** [comment]
> Actually, it didn't work as I had expected, it turns out that I couldn't reset the commit and push it again, so I modified the .json file back to its original format.

Did you try rebasing and dropping the commit? You can check out this [solution](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request).

**Comment by MMwandigha** [comment]
> > Actually, it didn't work as I had expected, it turns out that I couldn't reset the commit and push it again, so I modified the .json file back to its original format.
> 
> Did you try rebasing and dropping the commit? You can check out this [solution](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request).

image
Hmm I didn't try rebasing/dropping, but I tried doing git reset HEAD~1, removed the json file that was staged and tried to push but I came across this error

**Comment by MugoBrian** [comment]
Is your current branch `USH-1248` up to date with the remote `development` branch? I see in the hints, you could have tried the
following:
1. Ensure the `development` branch in the parent fork (ushahidi/platform-client-mzima) and your fork are in sync.
2. In your local `development` branch you run `git pull`.
Then try again. If it doesn't work you could use the flag -f to force when pushing the changes `git push -f origin USH-1248`.

You can check out the [solution](https://stackoverflow.com/questions/39399804/updates-were-rejected-because-the-tip-of-your-current-branch-is-behind-its-remot) provided.

PS: Be careful when using the flag `-f`, you can research more on the cons and pros of using it.

**Comment by MugoBrian** [comment]
Another thing also. When staging changes you can omit files like `package.json`, `package-lock.json`, `env.json`, especially if there are not crucial to your changes (i.e omitting them won't affect the functionality of your changes).

**Comment by MMwandigha** [comment]
> Is your current branch `USH-1248` up to date with the remote `development` branch? I see in the hints, you could have tried the following:
> 
> 1. Ensure the `development` branch in the parent fork (ushahidi/platform-client-mzima) and your fork are in sync.
> 2. In your local `development` branch you run `git pull`.
>    Then try again. If it doesn't work you could use the flag -f to force when pushing the changes `git push -f origin USH-1248`.
> 
> You can check out the [solution](https://stackoverflow.com/questions/39399804/updates-were-rejected-because-the-tip-of-your-current-branch-is-behind-its-remot) provided.
> 
> PS: Be careful when using the flag `-f`, you can research more on the cons and pros of using it.

Yes it was up to date

**Comment by MugoBrian** [comment]
> Yes it was up to date

As for now, your approach is still ok. You can try those steps as discussed.

**Comment by MMwandigha** [comment]
> > Yes it was up to date
> 
> As for now, your approach is still ok. You can try those steps as discussed.

Thanks @MugoBrian Ill give it a try

**Review by ushahidlee — APPROVED** [review]
Thanks @MMwandigha , looks good

**Pull request merged**
