### PR TITLE
Re-organize the end to end test files into folders

### PR DESCRIPTION
**Pull request by shakirandagire**
@AmTryingMyBest could you review the PR that handles [705](https://github.com/ushahidi/platform-client-mzima/issues/705)

### CODE REVIEW

**Comment by theobadha** [comment]
@shakirandagire please check and resolve the conflicts here.

**Comment by shakirandagire** [comment]
@AmTryingMyBest I have finished resolving the merge conflicts

**Comment by theobadha** [comment]
13 files changed! 😩 
Checking.

**Comment by shakirandagire** [comment]
@AmTryingMyBest Its because of the rearrangements made of the folders including renaming and removing redundant folders and files. Sorry for the many files

**Comment by theobadha** [comment]
Nothing to be sorry for, it is what it is. 
Thanks for your hard work! 👍

**Comment by shakirandagire** [comment]
You are welcome.

**Pull request merged**
