### PR TITLE
[Outreachy task submission] Proper translation of the 'Add new post' added to all language 

### PR DESCRIPTION
**Pull request by mo-gbolahan**
### Description:
Previously, when changing the language of the platform, the "Add new post" button remained unchanged, leading to inconsistency in language localization. To address this issue, the language JSON file was updated to include the appropriate translations for the "Add new post" button in each supported language. This ensures that the button dynamically changes its text to match the selected language, providing a more consistent and localized user experience.

### Checklist for Testing the Fix:
1. **Language Change Verification**:
   - Navigate to the platform and change the language settings to a different language.
   - Verify that the "Add new post" button text updates accordingly to reflect the selected language.

2. **Multi-Language Support**:
   - Test the platform in multiple supported languages to ensure that the "Add new post" button text changes accurately for each language option.
   - Confirm that the translations for the button text align with the language preferences selected by users.

3. **Text Localization Validation**:
   - Check the language JSON file to ensure that the appropriate translations for the "Add new post" button have been added for each supported language.
   - Verify that the translations are accurate and contextually appropriate for the button's function in each language.

4. **Consistency Across Interface**:
   - Ensure that the fix for the "Add new post" button extends to other interface elements, maintaining consistency in language localization throughout the platform.
   - Test other buttons, labels, and messages to confirm that they also update dynamically based on the selected language.

5. **Regression Testing**:
   - Verify that the implementation of dynamic language localization for the "Add new post" button does not introduce regressions or conflicts with other features or functionalities of the platform.
   - Test various scenarios and edge cases to ensure the stability and reliability of the language localization mechanism.

By following this checklist, you can ensure that the fix for the "Add new post" button language localization issue has been successfully implemented and thoroughly tested, improving the overall user experience of the platform for users across different language preferences.

@Angamanga

### CODE REVIEW

**Comment by mo-gbolahan** [comment]
https://github.com/ushahidi/platform/issues/4834

**Comment by MugoBrian** [comment]
Hello @mo-gbolahan, you forgot the Arabic Translation (one in the ar.json file).

**Comment by mo-gbolahan** [comment]
That must have been an  oversight, I've done that now

**Review by Angamanga — APPROVED** [review]
Thank you for this contribution! Approving this but will not merge it since translations live in a tool called Transifex. If you are interested in contributing with translations, please let me know and we'll sort out your access to Transifex 🙏

**Comment by Angamanga** [comment]
@Angamanga Not merging since translations lives in Transifex.

**Pull request closed without merging**
