### PR TITLE
fix empty space for private categories

### LINKED ISSUE #4743: Empty space for Only Me categories
How to reproduce:
Prerequisite steps
1. Login to your deployment
2. Click on "Settings"
3. Click on "Categories"
4. Create a category, set the visibility to "Only me"
5. Go back to "Settings"
6. Select "Surveys"
7. Create a survey or edit an old one
8. Click on "Add new field"
9. Select "Categories"
10. Select the category you just created
11. Save the survey
12. Add a new post to the survey
13. Make sure the category you added is selected
14. Click submit post
15. Go to feed-view
16. Publish the post

Reproduce the issue
As a logged out user,
1. Go to feed view
2. Locate the post you just created and click on it

**Expected behaviour**
Categories that the current user cannot see is not visible in any way under the category-field

**Actual behaviour**
There is a tag-icon with an empty space after it for the category that you just added.

Let's remove the marker (green circle) and not show any indication that a category is there but hidden.
Screenshot 2023-10-02 at 16 01 59
Screenshot 2023-10-02 at 16 03 20

---
Created automatically from USH-899 (https://linear.app/ushahidi/issue/USH-899/empty-space-for-only-me-categories)

### PR DESCRIPTION
**Pull request by Chiemezuo**
Fixes [#4743](https://github.com/ushahidi/platform/issues/4743)

# Summary
I added a conditional for the `category` div to render a tag from the returned array of categories only when `category.tag` is not empty.

## How to test the PR
1. Login to your deployment.
2. Click on "Settings".
3. Click on "Categories".
4. Create a category, set the visibility to "Only me".
5. Go back to "Settings".
6. Select "Surveys".
7. Create a survey or edit an old one.
8. Click on "Add new field".
9. Select "Categories".
10. Select the category you just created.
11. Save the survey.
12. Add a new post to the survey.
13. Make sure the category you added is selected.
14. Click submit post.
15. Go to the 'feed' view.
16. Publish the post.
17. Log out.
18. Go to the 'feed' view.
19. Locate the post you just created and click on it.
20. Compare the behavior you see to the one in the screenshot in issue [#4743](https://github.com/ushahidi/platform/issues/4743)

### CODE REVIEW

**Comment by Angamanga** [comment]
Thank you for the PR @Chiemezuo! Please add a short step by step checklist on how to test your changes when reviewing the PR 👍

**Comment by Chiemezuo** [comment]
Alright. I'll do just that @Angamanga

**Comment by Chiemezuo** [comment]
@Angamanga I've updated the PR comment with a step by step guide on how to test the PR.

**Comment by Angamanga** [comment]
Thank you @Chiemezuo! @webong Could you please review this PR?

**Comment by Angamanga** [comment]
@webong Reminding you to review this PR 👍

**Review by Angamanga — APPROVED** [review]

**Pull request merged**
