### PR TITLE
[Outreachy Task Submission] Code Refactoring on the Menu List Links and Non List Link components for the Sidebar. 

### PR DESCRIPTION
**Pull request by MugoBrian**
This pull request addresses this [issue](https://github.com/ushahidi/platform/issues/4896).

Fix:
The menu-list-links.component.html and menu-list-non-links.component.html files have undergone refactoring to align with the (DRY) Don't Repeat Yourself principle. I've eliminated redundant ng-template instances, which introduce unnecessary elements and potentially impact platform performance.

By refactoring these two components, accessibility enhancements are easier to implement singularly within a component, eliminating repetition. This approach aids in preventing regression bugs.

### CODE REVIEW

**Comment by MugoBrian** [comment]
Hello @Angamanga and @Ifycode. This PR is ready for review.

**Comment by MugoBrian** [comment]
Hello @Angamanga and @Ifycode , this PR Is ready for review.

**Review by Angamanga — APPROVED** [review]
Neat 🙌  Approved!

**Comment by Angamanga** [comment]
@Angamanga In QA

**Pull request merged**
