### PR TITLE
[Outreachy Task Submission] Add Hidden Button Value Text for Login & Signup Screens

### LINKED ISSUE #4757: [Outreachy Task Submission] Accessibility Issue with the 'show password' button value text in login/signup screens
# Intro
This is one of two accessibility issues I found with the 'Forgotten Password?' button in the login screen. Close to, but still very different from #4766. 

## Issue
The button for making passwords visible has no value text. ***This is a violation of WCAG Success Criterion 1.1.1 (Level A) - Non-text content***. [See](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html)

## Description.
***Success Criterion 1.1.1 (Level A) - Non-text content*** requires that all non-text content presented to users has a text alternative that serves the equivalent purpose, except for situations where the content is intended to be omitted by the author or is decorative in nature.

## Impact
Accessibility software that can either convert text to visuals (for deaf people), and braille (for blind people) will not work. People who cannot understand the meaning of images/icons would struggle with this. Additionally, there would be no way to search for visual content in a text-based manner. 

## Fix
Add a value text to the button. I will raise a PR for this, shortly.

### PR DESCRIPTION
**Pull request by Chiemezuo**
# Introduction
The "make password visible" button icon in both the `Login` and `Signup` view has a problem. The button has only an icon and has no value text. While this is just a stylistic choice, it raises an issue with any accessibility checking tool.  It does this because a button having no value text is a violation of WCAG Success Criterion 1.1.1 (Level A) - Non-text content. [See](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html). See a screenshot of the pertinent component:

image
> ***Note the SVG icon***

# How to Test the PR
## Manually Testing
1. Open your browser and log into your running Ushahidi deployment (from localhost).
2. Navigate to either the `login & signup` section.
3. Try right-clicking on the icon at the right side of the password input field of the screen and selecting 'inspect'.
4. View the properties. A few lines above the currently highlighted snippet, look for a `span` element with a class of `mzima-button__text`. See screenshot below:
image
5. You will not see any text in it.
6. Stop the running Ushahidi deployment in your terminal.
7. Checkout to this PR branch.
8. Re-run your Ushahidi deployment.
10. Repeat steps 1-4.
11. You will see a value in the `span` element this time around, and this text will be visually hidden.

## Using an Accessibility Checker
If you use a tool like [WAVE evaluation tool](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh), it's as simple as following steps 1 and 2 above, and then turning on the browser extension. It will flag the issue. Checkout to the PR and do this again, you will notice the issue is no longer flagged. 

## Dependency
This fix has a dependency on a previous [PR](https://github.com/ushahidi/platform-client-mzima/pull/860)

## Fixes
This fixes [#4757](https://github.com/ushahidi/platform/issues/4757)

### CODE REVIEW

**Review by Angamanga — CHANGES_REQUESTED** [review]
Just remove the !important from the visually-hidden class 🙏

**Comment by Chiemezuo** [comment]
Done that @Angamanga

**Review by Angamanga — APPROVED** [review]
Approved! 🎉

**Comment by Angamanga** [comment]
@Angamanga To consider for release

**Pull request closed without merging**
