### PR TITLE
CAM 2023 - All fixes for mzima's sidebar and parts of toolbar

### PR DESCRIPTION
**Pull request by Ifycode**
#### This pull requests fixes the following ticket(s)
- [USH-678] CAM 2023 Nav - Sidebar: Page links area and add post button (Desktop & Mobile)
- [USH-555] CAM 2023 Nav - Sidebar: Areas that are not page links (Desktop & Mobile)
- [USH-556] CAM 2023 Nav - Sidebar & Toolbar: Share button and donation button area (Desktop & Mobile)
- [USH-557] CAM 2023 Nav - Sidebar & Toolbar: Account Settings (Desktop & Mobile)
- [USH-558] CAM 2023 Unused Components - Data module, collection-modal component and Logo component

#

> **Note**
> The accessibility fixes and bug fixes are results of the Code Architecture fixes

#
#### Pull request fix summary
The fixes contained in this pull request are as follows:
- **Accessibility fixes** (logical order of elements on the page for mobile or smaller devices only):
   -  Page links and add post button are now the last elements on map view, data view, activity view and settings view
   - Fixes any other logical page order issues for elements within the sidebar, hamburger popup menu including the share & donation button area of the toolbar (generally for major elements shared across the 4 views)
- **Bug fixes:**
   - Disappearing elements on browser resize: 
      - Collection button in the sidebar no longer disappears on browser resize
      - Some other randomly not easily re-produceable disappearing elements on browser resize have also been fixed - in the sidebar area, toolbar and the hamburger popup menu area.
   - Flickering elements or styles on browser resize: Fixes flickering of hidden elements on browser resize from desktop to mobile and vice versa  - in the sidebar, hamburger popup menu, the share and donation buttons
   - Flickering elements/styles on page load/reload (on desktop): 
     - The deployment logo and details in the sidebar no longer hidden sometimes when loading or reloading the page
     - The Add post button no longer shows the mobile styling on page load or reload
- **Code Architecture fixes**
   - Code for desktop and smaller devices that live separately in the sidebar and toolbar now live together in their various components - more info in next bullet point.
   - Moved elements to their own components and injected where needed:
       - Page links - injected into the sidebar and at the bottom of the page for mobile. This aids/fixes accessibility as explained above/earlier.
       - The hamburger popup menu (i.e. the mobile menu)
       - Menu items that are not page links - injected into sidebar and hamburger popup menu respectively
       - Deployment details - Deployment logo and description's code have been merged into one code, and injected into the sidebar and hamburger popup menu respectively
       - Share and donation buttons - injected into toolbar and the hamburger popup menu respectively
       - Account settings and logout extracted into its own component (desktop only - the one for mobile is among the menu list items that are not page links)
   - Removed unused/forgotten/duplicated code e.g. the data module, the logo component, the duplicated collections component, scattered unused/forgotten/duplicated code fragments within the sidebar and toolbar.

#
#### Testing checklist
Help check the code re-structuring and logical arrangement of the elements/components mentioned in the summary above. Also help check the following: 
- [ ] Check that the functionality of all areas mentioned in the summary above are still working as expected
- [ ] Check that disappearing issues no longer exists elements/areas mentioned in the summary above
- [ ] Check that flickering issues no longer exists elements/areas mentioned in the summary above
- [ ] Check that QA-related items already worked on are not removed by mistake e.g. attributes used in code, functions, tests etc.

### CODE REVIEW

**Comment by Ifycode** [comment]
I have written a comprehensive summary and checklist in the [description above](https://github.com/ushahidi/platform-client-mzima/pull/461#issue-1838328971).

@miraxes @ushahidi/procoders Please help review.
We also need reviews (and at least one approval from the Ushahidi dev team before merging) cc: @tuxpiper @wisdom @Mh-Asmi 
And QA too @AmTryingMyBest 

I'll be away for a week. Please drop your reviews, if any change is needed I will make them when I come back. 

Also please do not make a direct change in this branch. If you need to make a change yourself, please create a branch from the `CAM-2023-nav-sidebar` branch and send as PR back into the branch.

@MugoBrian Your review is welcomed too.

**Comment by MugoBrian** [comment]
My reviews:

-  Functionality of all areas mentioned in the summary above are still working as expected
-  Disappearing issues no longer exists elements/areas mentioned in the summary above
-  Flickering issues no longer exists elements/areas mentioned in the summary above

New issues found:
- ~~Extra margin appearing in the account component for the laptop view.~~ [Fixed in another PR]
- ~~There's a delay for the sidebar menu non-links when switching from mobile to laptop.~~ [Fixed in this PR]
- There's a change in the order that the menu-list-non-links items appear in the sidebar.
 
@miraxes and procoders team ,@tuxpiper, and  @AmTryingMyBest  confirm this two issues.

**Comment by Ifycode** [comment]
Thank you @MugoBrian 
Although, we have talked about it on the meet call, I'm just still going to add it as a comment here.
You can send in a PR to fix any or both of the issues you have detected.

**Comment by miraxes** [comment]
@Ifycode  Should we merge #467 before merging everything in development?

**Comment by Ifycode** [comment]
@miraxes Thanks for asking.
That PR is part of CAM but is not part of this particular bulk fix.

You can just leave that PR, I will point it to the right base branch for a different bulk fix once the new base branch has been created.

**Comment by miraxes** [comment]
@Ifycode Some tests are failing, I tried to rerun it few times, didnt help.

**Comment by Ifycode** [comment]
Ok @AmTryingMyBest says he will help check and advice on what to do in the next hour.

**Comment by miraxes** [comment]
@Ifycode I did investigation and seems like you missing `data-qa="btn-settings"` attribute on sidebar setting button. And it can not open setting and add role. Or cypress can not find and access it.

**Comment by Ifycode** [comment]
Interesting... How come? 
@AmTryingMyBest says it passes locally for him.

Checking out your observation. Thank you @miraxes

**Comment by Ifycode** [comment]
The data-qa is added dynamically from the menu list object icon property:
````
[data-qa]="'btn-' + item.icon"
````
And as shown in the screenshots below, the data-qa btn-settings is applied. Please help me understand better @miraxes 

|Smaller devices| Desktop|
|--|--|
|Screenshot 2023-08-24 at 16 08 12|Screenshot 2023-08-24 at 16 07 00|

**Comment by miraxes** [comment]
@Ifycode So the error says 
`CypressError: `cy.click()` can only be called on a single element. Your subject contained 2 elements. ` So seems like you have more than one element with this attribute on a page.

**Comment by Ifycode** [comment]
I also suspect that this is caused by the "inject where needed" method I was using for the components. Though the settings button appears only once in the code base, it will show up in two positions on the page (i.e. desktop and mobile)- Inside the sidebar and at the bottom of the entire page... I'm wondering why it will pass locally and fail in the remote.
Let me experiment more...

**Comment by miraxes** [comment]
@Ifycode Any updates on this?

**Comment by Ifycode** [comment]
@miraxes Yes, I have found the issues based on experiments from this test PR 
- #547 

1. This is one problem: https://github.com/ushahidi/platform-client-mzima/pull/461#issuecomment-1692079215
2. The other problem has to do with the mzima-button with id of btn-login inside the login-form component (still wondering about this because I notice another PR submitted by dmitry had this same test failing). But for this particular CAM PR, I have an idea that it may be related to the menu-list I merged for desktop and mobile.

I'm still checking it out.

**Comment by Ifycode** [comment]
@miraxes Tests now pass 🤓 You can now help review.

**Comment by miraxes** [comment]
YAY! I'm good with changes, lets merge it and give some extra work for @AmTryingMyBest

**Review by miraxes — APPROVED** [review]

**Comment by Ifycode** [comment]
Ok @miraxes I have fixed the conflicts on the PR. Branch is now up to date 🎉

**Comment by miraxes** [comment]
Cool, and now we are facing same problem as 2 weeks ago 😃 Are we going to merge this right before snapshot on monday or after it? @tuxpiper

**Comment by Ifycode** [comment]
And it's passing again 🤣

**Comment by Ifycode** [comment]
I suspect that it passes or fails in relation to the last thing added into `development` branch?
Probably the last PR you merged had cleaned up the issue... So that when I'm updating again, it all passes 🤷🏽‍♀️

**Comment by tuxpiper** [comment]
Let's merge before, we will roll QA up with the pre-release checks. Please go ahead and merge @miraxes @Ifycode

**Pull request merged**
