### PR TITLE
fix Change placeholder text where all filter parameters are cleared #4735

### PR DESCRIPTION
**Pull request by Felysilver**
As per this issue [https://github.com/ushahidi/platform/issues/4735](url) I have fixed the placeholder text to be "Select a survey to show posts" even the issue discription suggested "select survey to show posts" 
select

### CODE REVIEW

**Comment by Felysilver** [comment]
@Angamanga, @tuxpiper I kindly ask if you can review this. Thanks!

**Comment by Felysilver** [comment]
@Angamanga may have a look at this PR. Thanks!

**Comment by Angamanga** [comment]
@Felysilver Thank you for your PR! Could you double-check so that string you changed are not used in other instances, for example, when there are actually no posts available?

**Review by Angamanga — CHANGES_REQUESTED** [review]
Could you double-check so that string you changed are not used in other instances, for example, when there are actually no posts available?

**Comment by Felysilver** [comment]
Thanks @Angamanga, I got your point, I am working on it!

**Comment by Angamanga** [comment]
This is fixed

**Pull request closed without merging**
