### PR TITLE
[Outreachy Task Submission] Accessibility And Language Support For Platform Tour Guide

### LINKED ISSUE #4787: [Outreachy Task Submission] Accessibility And Language Support For Platform Tour Guide
**Description**
The Tour Guide component in the platform client application lacks the ability for users to change their language before proceeding with the onboarding process. This limitation hinders users who prefer a language other than the default one from fully engaging with the onboarding experience. Without the ability to switch languages, users may encounter difficulties understanding instructions and navigating through the tour, potentially leading to frustration and incomplete onboarding.

**Expected behaviour**
The tour steps should support multiple languages so that users with other languages can follow through.

### PR DESCRIPTION
**Pull request by Aquilaafuadajo**
Resolves [#4787](https://github.com/ushahidi/platform/issues/4787) 

**Description:**
In this PR I have implemented a language select dropdown within the tour guide component. This enhancement empowers users to choose their preferred language at any step of the onboarding process, ensuring that language barriers do not impede their understanding and engagement. By incorporating this feature, users can seamlessly switch between languages, facilitating a smoother and more inclusive onboarding experience. Additionally, this solution aligns with Ushahidi's commitment to accessibility and user-centric design, fostering a more welcoming environment for users from diverse linguistic backgrounds.

Here's a video of the improved tour guide 👇🏽 

https://github.com/ushahidi/platform-client-mzima/assets/46582086/94d13b90-f061-4629-ad77-6fc8e11d91a7

**How To Test** 👇🏽 
1. Open the devtools
2. Navigate to application/local storage
3. Set USH_is_onboarding_done to false
4. Refresh the page to restart the tour guide

### CODE REVIEW

**Review by Angamanga — CHANGES_REQUESTED** [review]
Remove all the translations (but save them somewhere for Transifex :) 🙏 ). I also noticed that the onboarding does not get triggered when I go to help & settings and click on Onboarding when in this branch. Could you double-check if it still works in your environment?

**Comment by Aquilaafuadajo** [comment]
Okay thanks for the feedback @Angamanga, I'll look into this

**Comment by Aquilaafuadajo** [comment]
@Angamanga I just double-checked this and it works in my environment. I think you should refresh the page manually after switching to my branch then test. 

https://github.com/ushahidi/platform-client-mzima/assets/46582086/1b5843bc-a283-4174-86f0-cfee7f22f1ce

**Review by Angamanga — APPROVED** [review]
Works fine now, my browser must have been in a bad mood that day :D

**Comment by Aquilaafuadajo** [comment]
Haha 😆 that's fine. Thank you @Angamanga ❤️

**Pull request closed without merging**
