### PR TITLE
Fix delay in UI while permissions are loading

### PR DESCRIPTION
**Pull request by Angamanga**
This PR adds a spinner the permissions-list when editing or creating a role. 
How to test:
- Logged in as a user with role-creating permissions
- Go to settings, click on roles
- Click on a role or create a new one
- [ ] Spinner appears while the permissions are fetched from the API

Fix for issue https://linear.app/ushahidi/issue/USH-856/role-fields-appear-empty-for-a-sec-and-then-populated-with-data#comment-6cd75721

### CODE REVIEW

**Review by Ifycode — COMMENTED** [review]
Ok, nice idea that the spinner should only affect some content. The code looks ok. I'm just going to check and interact with the UI in a few minutes @Angamanga

**Comment by Ifycode** [comment]
Ok, so the flicker still happens - i.e. the input fields are empty briefly (and for admin and member roles, the delete button also appears briefly).
This is the part where you were referring to for state management right? @Angamanga

**Comment by Angamanga** [comment]
> Ok, so the flicker still happens - i.e. the input fields are empty briefly (and for admin and member roles, the delete button also appears briefly). This is the part where you were referring to for state management right? @Angamanga

Ahh, yes you are true, that is also affected by the delay :/ Good find! I will update the spinner to cover it all until the data is there 👍

**Comment by Angamanga** [comment]
@Ifycode I have updated the PR so the spinner covers the whole form 👍

**Review by Ifycode — APPROVED** [review]
This works to hide the flicker for now. So... 👍🏼

**Pull request merged**
