### PR TITLE
fix: change form elements handling search functionality to search elements

### PR DESCRIPTION
**Pull request by mannyAndem**
Changed form elements handling search functionality to search elements to better describe their purpose and improve accessibility.

### CODE REVIEW

**Comment by Angamanga** [comment]
@mannyAndem Could you please add a checklist for how to see the change in the UI and also, did you add an issue for this change? Could you please add the issue-number? Thank you :)

**Comment by mannyAndem** [comment]
Oh, forgot to add the issue number!

The pr fixes issue [4789](https://github.com/ushahidi/platform/issues/4789) which talked about the issue of form elements that handled search functionality not being clear about their intended purpose. Using the semantic search element would make it clear to screen readers and other assistive technologies what the form actually does.

There are also no ui changes :)

**Review by Angamanga — APPROVED** [review]
Interesting change! I have not worked with the <search> - element myself yet! Approved!

**Comment by Angamanga** [comment]
@angamanga Consider when filters are sorted out

**Comment by mannyAndem** [comment]
> Interesting change! I have not worked with the - element myself yet! Approved!

Thank you :) It's a fairly new element, was added to the spec in March last year.

**Pull request closed without merging**
