### PR TITLE
 Data View - sorting actions 

### LINKED ISSUE #613: Data View - sorting actions by date created
Sorting by Date created

- [ ] Login and navigate to Data View
- [ ] Click on Sorting
- [ ] Verify Date Created(Newest first) is highlighted/selected
- [ ] Verify posts are sorted by date created newest first
- [ ] Click on Sorting
- [ ] Click Date Created (Oldest first)
- [ ] Verify posts are sorted by date created oldest first

### PR DESCRIPTION
**Pull request by oyenuga17**
This one took a bit of time to come up with a flow that works 😅 

resolves #613 #611 #612 

**My Approach**

Since we can't always guarantee that the posts will be the same at all time, so we consistently generate two new posts for comparison each time the test runs. CreatedAt timestamp of Post 1 will always differ from that of Post 2, enabling us to verify which one comes before the other after we sort.

@AmTryingMyBest please help review 🙏

### CODE REVIEW

**Comment by theobadha** [comment]
@oyenuga17 actually, in the test environment that's in the CI, we can guarantee the posts and their order at all times. Each time the tests run in the CI environment, the platform is rebuilt so it will ALWAYS have the same data. Unless we expressly change this, and we can only change it by importing a fresh or different set of data (or database) :)

**Comment by oyenuga17** [comment]
> @oyenuga17 actually, in the test environment that's in the CI, we can guarantee the posts and their order at all times. Each time the tests run in the CI environment, the platform is rebuilt so it will ALWAYS have the same data. Unless we expressly change this, and we can only change it by importing a fresh or different set of data (or database) :)

Hmmm... that makes a lot of sense. 
@AmTryingMyBest please how can I get the data that's being imported by the CI so I can use that to compare when a sort action is carried out. Currently, the data in the staging environment is user generated data by us testers, so that's why I assumed it can't be guaranteed since it can be modified by anyone

**Comment by oyenuga17** [comment]
@AmTryingMyBest I came up with a different approach that might work for this.😅
I'll capture the contents of the first two posts instead of creating a new one, then use this two to compare... Please let me know what you think about this 🤔...

**Comment by theobadha** [comment]
Yeah that makes sense, no need to create a post. We already have tests that do that. I'm trying to figure out how to get this data to you contributors. I'll share that probably tomorrow.

**Comment by oyenuga17** [comment]
> Yeah that makes sense, no need to create a post. We already have tests that do that. I'm trying to figure out how to get this data to you contributors. I'll share that probably tomorrow.

Alright sounds good, thank you.

**Comment by oyenuga17** [comment]
Hi @AmTryingMyBest, please I'm waiting for the data so I can make changes to this test. It will also be very useful in #604 to verify the view sent in response 😊 🙏

**Pull request closed without merging**
