### PR TITLE
[Outreachy Task Submission] Make Categories Section Fully Accessible (Screen Readers and Keyboard Navigation)

### LINKED ISSUE #4779: [Outreachy Task Submission] Make Categories Section Fully Accessible (Screen Readers and Keyboard Navigation)
**Description**
Currently, the Categories section is not fully accessible. The following are the accessibility issues identified with this section: 
- Focused category item doesn't respond to enter keyboard event
- remove routerLink from h4 so the text don't receive additional focus when tabbing
- On Bulk actions, checkboxes do not respond to enter keyboard event
- Add Translation checkboxes do not respond to enter keyboard event

### PR DESCRIPTION
**Pull request by Aquilaafuadajo**
resolves [#4779](https://github.com/ushahidi/platform/issues/4779)

**Description**
Currently, the Categories section is not fully accessible. The following are the accessibility issues identified with this section: 

1. Focused category item doesn't respond to enter keyboard event
2. remove routerLink from h4 so the text don't receive additional focus when tabbing
3. On Bulk actions, checkboxes do not respond to enter keyboard event
4. Add Translation checkboxes do not respond to enter keyboard event

**How To Test**
Install [google chrome screen reader extension](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn) to accompany you
Using only your keyboard (tab = forward movement, shift + tab = backward movement, enter = click) do the following:
1. Navigate to settings/categories
2. Perform bulk action
3. Edit a category
4. Add translation

### CODE REVIEW

**Review by Angamanga — CHANGES_REQUESTED** [review]
Thank you for your submission! Works fine! I only noticed one thing, when I go and add a translation to a category from the keyboard, with and without voiceover on, the language does not get added to the dropdown, could you look into what caused that. It works in development so it must be a regression.

**Comment by Aquilaafuadajo** [comment]
Hmm... that's weird. Thank you @Angamanga I'll look into this right away

**Comment by Aquilaafuadajo** [comment]
Hi @Angamanga, sorry to bother you but please can you help me double check this again? I just tried to reproduce this behaviour and everything works fine on my end, the languages are being added to the dropdown when navigating using only keyboard. Below is a video of me testing this out using just keyboard


https://github.com/ushahidi/platform-client-mzima/assets/46582086/c6efdb2e-2f66-4374-823e-135b3e923549

**Review by Angamanga — APPROVED** [review]
@Aquilaafuadajo Strange, now it works fine! Approved!

**Comment by Aquilaafuadajo** [comment]
Thank you @Angamanga 🙏🏽

**Pull request closed without merging**
