### PR TITLE
 [Outreachy Task Submission] #4785 give page the right title

### PR DESCRIPTION
**Pull request by mo-gbolahan**

### CODE REVIEW

**Comment by mo-gbolahan** [comment]
link to the issue raised - https://github.com/ushahidi/platform/issues/4785

**Comment by Angamanga** [comment]
Thank you for your PR @mo-gbolahan  🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

**Comment by mo-gbolahan** [comment]
**Description:**
On the development branch, all pages displayed the same title, "Mzima Development Staging", which caused confusion as users couldn't differentiate between multiple open tabs. This issue was addressed by ensuring each page now has a proper and descriptive title, improving user experience and navigation.

**Testing Checklist:**
1. **Page Titles**: Verify that each page now has a unique and descriptive title.
2. **Tab Verification**: Open multiple tabs with different pages and ensure that the titles accurately reflect the content of each page.
3. **Cross-browser Testing**: Test the fix across different web browsers to ensure consistent behavior.
4. **Regression Testing**: Verify that the fix doesn't introduce any regressions or unexpected behavior in other parts of the application.
5. **Accessibility**: Check that the updated page titles are accessible and provide meaningful information for users relying on screen readers or other assistive technologies.
6. **Localization**: If applicable, ensure that the page titles are localized correctly according to the language settings.

@Angamanga

**Comment by mo-gbolahan** [comment]
**Description:**
On the development branch, all pages displayed the same title, "Mzima Development Staging", which caused confusion as users couldn't differentiate between multiple open tabs. This issue was addressed by ensuring each page now has a proper and descriptive title, improving user experience and navigation.

**Testing Checklist:**
1. **Page Titles**: Verify that each page now has a unique and descriptive title.
2. **Tab Verification**: Open multiple tabs with different pages and ensure that the titles accurately reflect the content of each page.
3. **Cross-browser Testing**: Test the fix across different web browsers to ensure consistent behavior.
4. **Regression Testing**: Verify that the fix doesn't introduce any regressions or unexpected behavior in other parts of the application.
5. **Accessibility**: Check that the updated page titles are accessible and provide meaningful information for users relying on screen readers or other assistive technologies.
6. **Localization**: If applicable, ensure that the page titles are localized correctly according to the language settings.

**Comment by mo-gbolahan** [comment]
https://github.com/ushahidi/platform/issues/4785

**Review by Angamanga — CHANGES_REQUESTED** [review]
Thank you for your contribution! Very good catch! Only one thing, could you remove the package-lock.json from the PR? It should not be committed if you don't add any new libraries or change versions. 🙏

**Comment by mo-gbolahan** [comment]
@Angamanga I have removed the package-lock file

**Review by Angamanga — CHANGES_REQUESTED** [review]
Sorry, I meant removing the package-lock file from the pullrequest, not deleting it entirely. Reset it to its original state, as it is in the development-branch right now and then this is approved 👍

**Comment by mo-gbolahan** [comment]
> Sorry, I meant removing the package-lock file from the pullrequest, not deleting it entirely. Reset it to its original state, as it is in the development-branch right now and then this is approved 👍

I've added the package.json file as requested

**Comment by Aquilaafuadajo** [comment]
Hi @mo-gbolahan I think what @Angamanga is saying here is that you should reset the package-lock file back to it's original state on the development branch.
If you notice, your pr has 2 file changes(package-lock and app-routing.module) when it should be just one file change.

**Pull request closed without merging**
