### PR TITLE
[Fix] category name form showing required validation when no user interaction has happened

### LINKED ISSUE #4742: Category name is required
To reproduce:
1. Prerequisite: Logged in user
2. Click on Settings and select "Categories
3. Click on "Add category"

**Expected behaviour**
The text"Category name is required" does not appear until the user has attempted to create a category and left the field blank. 

**Actual behaviour**

The text "Category name is required" shows when Create Category page is opened.

https://github.com/ushahidi/platform/assets/8624777/dfc5ba1a-e4b8-4621-9d00-6de29479c11d

---
Created automatically from USH-781 (https://linear.app/ushahidi/issue/USH-781/category-name-is-required)

### PR DESCRIPTION
**Pull request by Aquilaafuadajo**
@Angamanga @tuxpiper please help review, this resolves [#4724](https://github.com/ushahidi/platform/issues/4742)
Here's a video of the fixed version

**How to test this**

1. go to settings
2. click categories
3. click add category

https://github.com/ushahidi/platform-client-mzima/assets/46582086/abe61912-5976-4f8d-941b-a6b9f0da5ef8

### CODE REVIEW

**Comment by Angamanga** [comment]
Thank you for your PR @Aquilaafuadajo 🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

**Comment by Aquilaafuadajo** [comment]
Thanks for the review @Angamanga, I have updated my comment 🙏🏽

**Review by Angamanga — APPROVED** [review]
Works fine and follows the pattern we have elsewhere in the code 👍 . Just a curious question, was it adding the noWhitespaceValidator or moving the initialisation of the form that made it work?

**Comment by Angamanga** [comment]
@Mh-Asmi For next release 👍

**Comment by Aquilaafuadajo** [comment]
> Works fine and follows the pattern we have elsewhere in the code 👍 . Just a curious question, was it adding the noWhitespaceValidator or moving the initialisation of the form that made it work?

No @Angamanga that change isn't required. I followed the steps used in survey-item and initially thought it had to do with the problem while trying to figure out the bug but when I figured it out I realised that the change wasn't a bad refactor too so I left it.

**Pull request merged**
