### PR TITLE
Reword survey error message and highlight survey name field (#4736)

### LINKED ISSUE #4736: Reword error message when creating a survey
I added a "+" character when creating a Survey in the Survey name field. The error message that came up was "please recheck the your inputs"
**Expected Behavior**

Highlight field with issue

Correct the wording to be grammatically correct, and descriptive. We want to tell the user a field has invalid characters or input.

https://github.com/ushahidi/platform/assets/8624777/5c82a9a7-2b44-4bd3-9bf2-8c8cf25bfce8

---
Created automatically from USH-878 (https://linear.app/ushahidi/issue/USH-878/reword-error-message-when-creating-a-survey)

### PR DESCRIPTION
**Pull request by blessingpeters**
This pull request makes the following changes:

- Rewords the error message when creating a survey
- Highlights the field with issue

Fixes ushahidi/platform#4736

Here's a video of how it works now

https://github.com/ushahidi/platform-client-mzima/assets/68845318/a477e45d-0e17-40c1-b344-5eeb3c68616f

@Angamanga @Ifycode please review.

### CODE REVIEW

**Review by Angamanga — CHANGES_REQUESTED** [review]
Thank you for your contribution. Is it possible to add the error-message just below the affected field as well?

Another curious question, is it possible to detect this error before saving the post and sending the data to the API? That would make everything a bit faster I think.

**Comment by blessingpeters** [comment]
> Thank you for your contribution. Is it possible to add the error-message just below the affected field as well?
> 
> Another curious question, is it possible to detect this error before saving the post and sending the data to the API? That would make everything a bit faster I think.

Thank you @Angamanga for the review and the excellent suggestion! It's definitely a more efficient approach. I'll revert back with updates and changes made.

**Comment by blessingpeters** [comment]
Hi @Angamanga  I've implemented the changes requested. Error messages are now displayed directly below the fields upon validation errors, and we're catching these errors before attempting to save or send data to the API. 
Please review.

https://github.com/ushahidi/platform-client-mzima/assets/68845318/06cba880-4fb9-4738-94af-b6601c4149bf

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution! Approved!

**Pull request merged**
