### PR TITLE
Add Mobile Data Source Label

### PR DESCRIPTION
**Pull request by webong**
- Add mobile as a data source to search helper file

### CODE REVIEW

**Comment by webong** [comment]
@tuxpiper @Mh-Asmi 

This PR needs to go out for the ability to see Mobile Source Label in the Search Bar

**Review by Angamanga — APPROVED** [review]
This works fine! Approved. 

Question though, should there be a mobile-label in the app too? I see there is a similar file in mobile-mzima but no "Mobile"-source added there.

**Comment by tuxpiper** [comment]
> This works fine! Approved.
> 
> Question though, should there be a mobile-label in the app too? I see there is a similar file in mobile-mzima but no "Mobile"-source added there.

I would definitely think so, this bit of functionality should be equivalent both on the web and mobile app! Nice catch @Angamanga  ! 
Could you please create a sub-issue  in https://linear.app/ushahidi/issue/USH-987/add-mobile-app-as-a-data-source-label-at-the-backend  ? Urgent priority .

**Comment by Angamanga** [comment]
Sub-issue added: https://linear.app/ushahidi/issue/USH-1085/add-mobile-app-as-a-data-source-label-in-mobile-client-code

**Pull request merged**
