### PR TITLE
E2e tests for Unique selectors for Posts, EditPost, Collections, Categories

### PR DESCRIPTION
**Pull request by shakirandagire**
@AmTryingMyBest could you help me review the PR that covers the [issues](https://github.com/ushahidi/platform-client-mzima/issues/654)

### CODE REVIEW

**Comment by theobadha** [comment]
Looks good! 👍

**Comment by theobadha** [comment]
@shakirandagire please change this to draft if you're still working on it, and then submit it when fully done. :)

**Comment by shakirandagire** [comment]
@AmTryingMyBestSorry had not put this in drafts. I am done working on it at the moment. You can review it please.

**Comment by shakirandagire** [comment]
@AmTryingMyBest I have created unique selectors for most of the elements except for `.mat-button.mat-stroked-button` that selects the date-time of the Post.
I have tried various ways to target the button but I am currently unable to since even locating the button is a problem.
Could you please advise me on how I can fix this.
Thank you

**Comment by oyenuga17** [comment]
> @AmTryingMyBest I have created unique selectors for most of the elements except for `.mat-button.mat-stroked-button` that selects the date-time of the Post. I have tried various ways to target the button but I am currently unable to since even locating the button is a problem. Could you please advise me on how I can fix this. Thank you

@shakirandagire this one is quite tricky and it might be one of those cases were we have to rely on classes for selectors. Having looked at this, I realized the date-picker component is from angular material and it's impossible to add unique selector for the check button that's being rendered inside the date-picker component. 

Although this is just what I think... we can wait for @AmTryingMyBest's input. 😊

**Comment by shakirandagire** [comment]
@oyenuga17 Thank you for the feedback. I realized that as well and got stuck on how to proceed.
Looking forward to @AmTryingMyBest 's feedback so that I can remove this from Draft PR.

**Comment by oyenuga17** [comment]
> @oyenuga17 Thank you for the feedback. I realized that as well and got stuck on how to proceed. Looking forward to @AmTryingMyBest 's feedback so that I can remove this from Draft PR.

You're welcome. Happy to help 😊

**Comment by theobadha** [comment]
> @AmTryingMyBest I have created unique selectors for most of the elements except for `.mat-button.mat-stroked-button` that selects the date-time of the Post. I have tried various ways to target the button but I am currently unable to since even locating the button is a problem. Could you please advise me on how I can fix this. Thank you

It's fine, you don't have to have gotten them all at once. We can always add more on a need-to basis as we go, this definitely doesn't block the pr.   :)

**Pull request merged**
