### PR TITLE
Hotfix USH 1028 - Add deployment url manually

### PR DESCRIPTION
**Pull request by webong**
- Fixes Case Sensitive issue when adding deployment URL.

### CODE REVIEW

**Comment by tuxpiper** [comment]
There seem to be a number of changes here , aside from the case sensitivity stuff. @ushahidlee can you please review?

**Comment by webong** [comment]
> There seem to be a number of changes here , aside from the case sensitivity stuff. @ushahidlee can you please review?

@lee ... those changes were from me trying to get capacitor working, some deps were out of sync for me.

**Review by ushahidlee — APPROVED** [review]
All good!

**Comment by tuxpiper** [comment]
Cherry-picked into development here: 679903972d252585b84495786a75e76f958acfd4

**Pull request merged**
