### PR TITLE
fixed select all button for the Data view page

### PR DESCRIPTION
**Pull request by rajutkarsh07**
Resolving issue #866 

### Description
Fixes the `Select All` button functionality in the Surveys menu on the Data View page. Allows users to select all items.

[fix.webm](https://github.com/ushahidi/platform-client-mzima/assets/49344502/b2be1a2c-dfcb-4444-9a39-9b47691e0cb4)

### CODE REVIEW

**Comment by Angamanga** [comment]
@Thank you for your PR @rajutkarsh07  🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

**Comment by rajutkarsh07** [comment]
@Angamanga I have updated the description

**Review by Angamanga — CHANGES_REQUESTED** [review]
Thank you for your contribution! This is correct, but could you please add back [data-qa]="'clear'"? It is needed for our e2e tests.

**Comment by rajutkarsh07** [comment]
@Angamanga I have added [data-qa]="'clear'" 
Please review it and merge it

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution! Approved 👍

**Comment by Angamanga** [comment]
@Angamanga To consider for next release

**Pull request merged**
