### PR TITLE
[Outreachy Task Submission] Improve Font Size For Survey Fields In Data Import Page.

### PR DESCRIPTION
**Pull request by MugoBrian**
This PR is a fix for this [issue](https://github.com/ushahidi/platform/issues/4865)
**Problem:**
The small font size for table cells under survey fields in the data import page makes the information difficult to read, creating a barrier for users with visual impairments. This violates accessibility guidelines.

**Fix:**
The font size for survey fields in the data import page has been changed from 12px to 16px.

**Steps to Reproduce the Fix:**

1. Log in to the platform and navigate to /settings/data-import.
2. Import a CSV file and choose a survey.
3. Select a survey, in my case 'Simple Survey', in the data import, the font size for the table cells beneath the survey is much bigger. This makes the information easier to read.

See the screenshot below for reference.
Screenshot from 2024-03-23 17-41-43

### CODE REVIEW

**Comment by MugoBrian** [comment]
Hello @Angamanga, this PR is ready for review.

**Review by Angamanga — APPROVED** [review]
Thank you for this contribution, its the small details that makes the difference :)

**Comment by Angamanga** [comment]
@Angamanga To consider for next release

**Comment by MugoBrian** [comment]
> Thank you for this contribution, its the small details that makes the difference :)

It's always the small things that matter also. :100:

**Comment by Angamanga** [comment]
@Timonize Could you please check here if this is a font-size we want to change to? (I think so 👍 ).

**Pull request closed without merging**
